### ISSUE TITLE
Stack of pid = xx missing

### ISSUE THREAD

**Issue by paramikoooo** [resilar/psyscall#2]
When I compile and run this code on ARM v7 
For example 
./psyscall xxx getuid

Error:

Stack of pid = xx missing
[xxx] psyscall() errno=22 (Invalid argements)

The remote process is statically compiled so maybe this project can't find libc.

**Comment by resilar** [comment]
>The remote process is statically compiled so maybe this project can't find libc.

Correct. The error message was misleading and simply incorrect. Commit aeee3c6 fixes the message.

**Comment by resilar** [comment]
Supporting statically linked binaries are out of the scope of this project. If you want to inject syscalls or regular function calls on a **specific** target architecture, just write a platform dependent tool for it using ptrace. Trust me, it is not too difficult :)

psyscall aims for a perverse form of "portability" by determining the platform's PC/SP/RET registers at runtime by exploiting semantics (and "reliable" undefined behavior) of C language. For serious projects, you are better off by accessing the target architecture's registers directly, for example, with named register constants. Then you do not have to do awful hacks at runtime to determine which index of PTRACE_GETREGS array corresponds to the stack pointer register, instruction pointer etc.

However, one might think that psyscall could easily find the syscall instruction encoding with similar "hacks" in order to support statically linked binaries by exploiting a single syscall instruction somewhere in the target process address space. That is true, but not sufficient for reliable portable syscall injection to statically linked binaries. For example, we need the libc's syscall wrapper for handling calling conventions. The problem isn't the syscall instruction itself, but finding out which registers (or stack offsets) are used to pass arguments to the kernel with the raw syscall interface. The libc syscall wrapper does the work for us by convertin C function calls to the kernel syscall convention.
